import Head from 'next/head'
import React from 'react'
import { useEffect, useRef, useState } from 'react'
import styles from './home.module.scss'
import TasksList from './tasksList'

export default function Home() {
  const [tasks, setTasks] = useState([])

  useEffect(() => {
    let tasks1: any = localStorage.getItem('tasks')
    const tasks = tasks1 ? JSON.parse(tasks1.toString()) : []
    setTasks(tasks ? tasks : [])
  }, [])

  const inputRef = useRef(null)

  const handleClick = () => {
    // @ts-ignore
    tasks.push(inputRef.current.value)
    setTasks(tasks)
    localStorage.setItem('tasks', JSON.stringify(tasks))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Todo App</h1>
        <p className={styles.description}>What are your tasks for today.</p>
        <form className='container'>
          <input type='text' ref={inputRef} className='animated-button1' />
          <a href='#' className='animated-button1' onClick={handleClick}>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Button
          </a>
          {/* <input id='task' type='submit' onClick={handleClick} /> */}
        </form>

        <br />
        <div id='tasksTable'>{TasksList(tasks)}</div>
      </main>

      <footer className={styles.footer}>
        <a href='https://loop.org.il' target='_blank' rel='noopener noreferrer'>
          <p> Created With {'<'}3 by Loopers </p>
        </a>
      </footer>
    </div>
  )
}
